name: efood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.1
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6
  firebase_core: ^1.2.1
  flutter_local_notifications: ^9.1.5
  path_provider: ^2.0.9
  url_strategy: ^0.2.0
  pin_code_fields: ^7.3.0
  mailer: ^5.0.2
  pay: ^1.0.1
  geolocator: ^8.0.1
  google_maps_flutter: ^2.1.2
  google_maps_flutter_web: ^0.3.2+1
  flutter_typeahead: ^3.2.4
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.4+4
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  webview_flutter: ^3.0.0
  flutter_widget_from_html_core: ^0.8.4
  url_launcher: ^6.0.17
  http: ^0.13.4
  pointer_interceptor: ^0.9.0+1
  phone_number: ^0.12.0+1
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.0
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.1
  flutter_toggle_tab: ^1.1.7
  change_app_package_name: ^1.1.0
  flutter_stripe:
  flutter_svg:
  intl_phone_number_input:
#  flutter_stripe:
    #^2:2:0:
# published key = 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
# API key  =  pk_live_51JCskPGJw4LwnASwj8uzAK4PxhtFuAX8YLuLoTHpMMymSAVxaTv84NcTwNCTsVYXmz20B4eivhLWw8FSJwsKXCnw001raIyiZz
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_messaging: 11.2.8
  firebase_core_platform_interface: 4.5.1
  modal_bottom_sheet: ^3.0.0-pre

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/gpay.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900